// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ActivityCard: typeof import('./src/components/ActivityCard.vue')['default']
    AddBalance: typeof import('./src/components/AddBalance.vue')['default']
    AddCardForm: typeof import('./src/components/AddCardForm.vue')['default']
    BalanceHistoryCard: typeof import('./src/components/balance/BalanceHistoryCard.vue')['default']
    BalanceItem: typeof import('./src/components/balance/BalanceItem.vue')['default']
    BookingBlock: typeof import('./src/components/BookingBlock.vue')['default']
    BookingClubInfo: typeof import('./src/components/BookingClubInfo.vue')['default']
    CardsList: typeof import('./src/components/CardsList.vue')['default']
    ClubCard: typeof import('./src/components/ClubCard.vue')['default']
    CurrentBalance: typeof import('./src/components/CurrentBalance.vue')['default']
    EmojiBar: typeof import('./src/components/locations/EmojiBar.vue')['default']
    ErrorMessage: typeof import('./src/components/ErrorMessage.vue')['default']
    FromToDatePicker: typeof import('./src/components/balance/FromToDatePicker.vue')['default']
    FromToDateTimePicker: typeof import('./src/components/balance/FromToDateTimePicker.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    IconClose: typeof import('./src/components/icons/IconClose.vue')['default']
    IconCurrentLocation: typeof import('./src/components/icons/IconCurrentLocation.vue')['default']
    IconEmail: typeof import('./src/components/icons/IconEmail.vue')['default']
    IconEye: typeof import('./src/components/icons/IconEye.vue')['default']
    IconFriends: typeof import('./src/components/icons/IconFriends.vue')['default']
    IconFullscreen: typeof import('./src/components/icons/IconFullscreen.vue')['default']
    IconLocation: typeof import('./src/components/icons/IconLocation.vue')['default']
    IcRoundLogOut: typeof import('./src/components/icons/IcRoundLogOut.vue')['default']
    IcRoundQrCode: typeof import('./src/components/icons/IcRoundQrCode.vue')['default']
    LocPermitionDialog: typeof import('./src/components/locations/LocPermitionDialog.vue')['default']
    MainMenu: typeof import('./src/components/MainMenu.vue')['default']
    MainSwiper: typeof import('./src/components/MainSwiper.vue')['default']
    MapDG: typeof import('./src/components/locations/MapDG.vue')['default']
    MapGL: typeof import('./src/components/locations/MapGL.vue')['default']
    MenuItem: typeof import('./src/components/MenuItem.vue')['default']
    NewsCard: typeof import('./src/components/NewsCard.vue')['default']
    PcCategoryPicker: typeof import('./src/components/PcCategoryPicker.vue')['default']
    PcPicker: typeof import('./src/components/PcPicker.vue')['default']
    PlayUntilModal: typeof import('./src/components/PlayUntilModal.vue')['default']
    PrimaryButton: typeof import('./src/components/PrimaryButton.vue')['default']
    QRcode: typeof import('./src/components/QRcode.vue')['default']
    QRSlideTop: typeof import('./src/components/qrSlide/QRSlideTop.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SimpleButton: typeof import('./src/components/SimpleButton.vue')['default']
    Slider: typeof import('./src/components/Slider.vue')['default']
    SuccessCheckmark: typeof import('./src/components/SuccessCheckmark.vue')['default']
    TimeWheel: typeof import('./src/components/TimeWheel.vue')['default']
    TransactionsList: typeof import('./src/components/TransactionsList.vue')['default']
  }
}
