export const errorNames = {
  'Incorrect email or password.': 'Неправильный адрес электронной почты или пароль.',
  'Authentication credentials were not provided.': 'Вы не авторизованы',
  'Enter a valid email address.': 'Введите корректный электронный адрес.',
  'Incorrect password.': 'Неверный пароль.',
  'The password is too similar to the email address.': 'Пароль слишком похож на адрес электронной почты.',
  'The password is too similar to the first name.': 'Пароль слишком похож на имя.',
  'Ensure this field has no more than 128 characters.': 'Пожалуйста, используйте не более 128 символов.',
  'This field is required.': 'Это поле обязательно для заполнения.',
  'This field must be at least 8 characters long.': 'Это поле должно быть не менее 8 символов.',
  'This field may not be null.': 'Это поле не может быть пустым.',
  'Could not create account with this email.': 'Не удалось создать аккаунт с этим адресом электронной почты.',
  'This password is entirely numeric.': 'Этот пароль состоит только из цифр, сделайте его сложнее.',
  'This password is too short. It must contain at least 8 characters.': 'Этот пароль слишком короткий. Он должен содержать не менее 8 символов.',
  'This password is too common.': 'Этот пароль слишком популярный.',
  'Insufficient funds': 'На балансе должно быть минимум 1000 тенге',
  'User has no balance': 'Вам необходимо пополнить баланс',
  'User has active reservations': 'У вас уже есть активная бронь',
  'Reservation already exists for this time': 'На это время уже есть бронирование',
  first_name: 'Имя',
  last_name: 'Фамилия',
  email: 'Email',
  password: 'Password',
}
